[package]
name = "bw6-verifier-circuit"
version = "0.1.0"
edition = "2021"
description = "BW6-767 APK proof verifier as a BN254 Groth16 circuit"

[dependencies]
ark-std = { version = "0.5", default-features = false }
ark-ff = { version = "0.5", default-features = false }
ark-ec = { version = "0.5", default-features = false }
ark-r1cs-std = { version = "0.5", default-features = false }
ark-relations = { version = "0.5", default-features = false }
ark-serialize = { version = "0.5", default-features = false }
ark-snark = { version = "0.5", default-features = false }
ark-poly = { version = "0.5", default-features = false }

ark-bw6-767 = { version = "0.5", default-features = false }
ark-bls12-381 = { version = "0.5", default-features = false, features = ["curve"] }
ark-bn254 = { version = "0.5", default-features = false, features = ["curve"] }
ark-groth16 = { version = "0.5", default-features = false }

[dev-dependencies]
ark-std = { version = "0.5", features = ["std"] }
apk-proofs = { path = "../bw6" }
w3f-pcs = { git = "https://github.com/polytope-labs/fflonk", branch = "fix/remove-two-adicity-check" }
merlin = "3.0"

[features]
default = ["std"]
std = [
    "ark-std/std",
    "ark-ff/std",
    "ark-ec/std",
    "ark-r1cs-std/std",
    "ark-relations/std",
    "ark-bw6-767/std",
    "ark-bls12-381/std",
    "ark-bn254/std",
    "ark-groth16/std",
]
